apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: --
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: '--:2081/repository/gib-helm/'
    targetRevision: 0.0.1-SNAPSHOT
    chart: server
    helm:
      valueFiles:
        - test-values.yaml
  project: --
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
      - FailOnSharedResource=true
    automated:
      prune: true
      selfHeal: true
