//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.21 at 09:29:26 PM AST 
//


package tr.gov.gib.evdbelge.evdbelgeteblig.client.codes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tr.gov.gib.evdbelge.evdbelgeteblig.client.codes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TebligatEntry_QNAME = new QName("http://webservice.etebligat.vedop2014.gib.gov.tr/", "TebligatEntry");
    private final static QName _Deliver_QNAME = new QName("http://webservice.etebligat.vedop2014.gib.gov.tr/", "deliver");
    private final static QName _DeliverResponse_QNAME = new QName("http://webservice.etebligat.vedop2014.gib.gov.tr/", "deliverResponse");
    private final static QName _IsDelivered_QNAME = new QName("http://webservice.etebligat.vedop2014.gib.gov.tr/", "isDelivered");
    private final static QName _IsDeliveredResponse_QNAME = new QName("http://webservice.etebligat.vedop2014.gib.gov.tr/", "isDeliveredResponse");
    private final static QName _IsDeliveredResponseReturn_QNAME = new QName("", "return");
    private final static QName _DeliverArg0_QNAME = new QName("", "arg0");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tr.gov.gib.evdbelge.evdbelgeteblig.client.codes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TebligatEntry }
     * 
     */
    public TebligatEntry createTebligatEntry() {
        return new TebligatEntry();
    }

    /**
     * Create an instance of {@link Deliver }
     * 
     */
    public Deliver createDeliver() {
        return new Deliver();
    }

    /**
     * Create an instance of {@link DeliverResponse }
     * 
     */
    public DeliverResponse createDeliverResponse() {
        return new DeliverResponse();
    }

    /**
     * Create an instance of {@link IsDelivered }
     * 
     */
    public IsDelivered createIsDelivered() {
        return new IsDelivered();
    }

    /**
     * Create an instance of {@link IsDeliveredResponse }
     * 
     */
    public IsDeliveredResponse createIsDeliveredResponse() {
        return new IsDeliveredResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TebligatEntry }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TebligatEntry }{@code >}
     */
    @XmlElementDecl(namespace = "http://webservice.etebligat.vedop2014.gib.gov.tr/", name = "TebligatEntry")
    public JAXBElement<TebligatEntry> createTebligatEntry(TebligatEntry value) {
        return new JAXBElement<TebligatEntry>(_TebligatEntry_QNAME, TebligatEntry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Deliver }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Deliver }{@code >}
     */
    @XmlElementDecl(namespace = "http://webservice.etebligat.vedop2014.gib.gov.tr/", name = "deliver")
    public JAXBElement<Deliver> createDeliver(Deliver value) {
        return new JAXBElement<Deliver>(_Deliver_QNAME, Deliver.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliverResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeliverResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://webservice.etebligat.vedop2014.gib.gov.tr/", name = "deliverResponse")
    public JAXBElement<DeliverResponse> createDeliverResponse(DeliverResponse value) {
        return new JAXBElement<DeliverResponse>(_DeliverResponse_QNAME, DeliverResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsDelivered }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IsDelivered }{@code >}
     */
    @XmlElementDecl(namespace = "http://webservice.etebligat.vedop2014.gib.gov.tr/", name = "isDelivered")
    public JAXBElement<IsDelivered> createIsDelivered(IsDelivered value) {
        return new JAXBElement<IsDelivered>(_IsDelivered_QNAME, IsDelivered.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsDeliveredResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IsDeliveredResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://webservice.etebligat.vedop2014.gib.gov.tr/", name = "isDeliveredResponse")
    public JAXBElement<IsDeliveredResponse> createIsDeliveredResponse(IsDeliveredResponse value) {
        return new JAXBElement<IsDeliveredResponse>(_IsDeliveredResponse_QNAME, IsDeliveredResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "", name = "return", scope = IsDeliveredResponse.class)
    public JAXBElement<byte[]> createIsDeliveredResponseReturn(byte[] value) {
        return new JAXBElement<byte[]>(_IsDeliveredResponseReturn_QNAME, byte[].class, IsDeliveredResponse.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "", name = "arg0", scope = Deliver.class)
    public JAXBElement<byte[]> createDeliverArg0(byte[] value) {
        return new JAXBElement<byte[]>(_DeliverArg0_QNAME, byte[].class, Deliver.class, ((byte[]) value));
    }

}
