//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.21 at 09:29:26 PM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservice.etebligat.vedop2014.gib.gov.tr/")
package tr.gov.gib.evdbelge.evdbelgeteblig.client.codes;
